name: New Release - Toolchain

on:
  push:
    tags:
      - my-toolchain_v*
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: '0.0.0'
        required: true
    
env:
  RELEASE: ${{ github.event.inputs.version }}

jobs:
  on-release:
    name: On Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get release version
        if: ${{ env.RELEASE == null }}
        id: version
        run: |
          echo "${GITHUB_REF#refs/*/my-toolchain_v}"
