name: PR - Checks

on:
  workflow_dispatch: 
  
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
                    
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v36.1.1