name: PR - Checks

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      matrix: ${{ steps.filter.outputs.changes }}
      build-comment: ${{ steps.create.outputs.comment-id }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEV_BOT_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          token: ${{ secrets.DEV_BOT_TOKEN }}

      - name: User
        run: 
          echo "PR User ${{github.event.pull_request.user.login}}"
          echo "Issue User ${{github.event.issue.user.login}}"

      - name: Renovate
        run: |
          node common/scripts/install-run-rush.js update
