name: Spike

on:
  workflow_dispatch:
    inputs:
      version:
        default: '0.0.0'
        required: true
        description: "My App version"
      
env:
  RELEASE: ${{ github.event.inputs.version }}

jobs:
  build_push_image:
    name: Spike
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'my-app_v${{env.RELEASE}}'

      - name: Spike
        run: |
          git status
