name: Spike

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, edited]

jobs:
  build_push_image:
    name: Spike
    runs-on: ubuntu-latest
    steps:
      - name: Clean up label
        uses: egmacke/action-remove-labels@v1.3.1
        if: success() && github.event.pull_request
        with:
          labels: build-fail
          fail_on_error: false
          allow_missing: true
          github_token: ${{ secrets.DEV_BOT_TOKEN }}
      
