name: Spike

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, edited]

env:
  LABEL: build-fail

jobs:
  build_push_image:
    name: Spike
    runs-on: ubuntu-latest
    steps:
      - name: Clean up label
        uses: egmacke/action-remove-labels@v1.3.1
        with:
          labels: ${{ env.LABEL }}
          allow_missing: true
          
      # - name: Add label
      #   uses: actions-ecosystem/action-remove-labels@v1
      #   with:
      #     labels: ${{ env.LABEL }}
      
      - name: Test for label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: ${{ env.LABEL }}
          
