name: Spike

on:
  workflow_dispatch:
    inputs:
      version:
        default: '0.0.0'
        required: true
        description: "SynapCore version"
      
env:
  RELEASE: ${{ github.event.inputs.version }}

jobs:
  build_push_image:
    name: Spike
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get release version
        if: ${{ env.RELEASE != '0.0.0' }}
        id: version
        run: |
          echo "RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV        
      
      - name: Spike
        run: echo ${{ env.RELEASE }}
