name: Spike

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, edited]

env:
  LABEL: build-fail

jobs:
  spike:
    name: Spike
    runs-on: ubuntu-latest
    steps:
      - name: Clean up label
        uses: egmacke/action-remove-labels@v1.3.1
        with:
          labels: ${{ env.LABEL }}
          allow_missing: true
          
      # - name: Add label
      #   uses: actions-ecosystem/action-remove-labels@v1
      #   with:
      #     labels: ${{ env.LABEL }}
          
  ci-build-check:
    if: always() && github.event.pull_request
    runs-on: ubuntu-latest
    name: CI Build Check
    needs: spike
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: ${{ env.LABEL }}
